import MasterHeader from "@/components/MasterHeader";
import "./globals.css";
import { Inter } from "next/font/google";
import MasterFooter from "@/components/MasterFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Simple Blog",
  description: "Generated by Simple Blog",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>        
        <MasterHeader />
        {children}
        <MasterFooter />
      </body>
    </html>
  );
}
